# Generated by Django 5.0 on 2024-02-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('bio', models.TextField()),
                ('slug', models.SlugField(max_length=300)),
                ('img', models.ImageField(upload_to='index/img')),
            ],
        ),
    ]
