# Generated by Django 5.0 on 2024-02-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('img', models.ImageField(upload_to='index/img')),
                ('slug', models.SlugField(max_length=300)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
