# Generated by Django 5.0 on 2024-02-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_about_img_alter_about_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='about/img')),
                ('slug', models.SlugField(max_length=300)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='img',
            field=models.ImageField(upload_to='index/img'),
        ),
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
